namespace ZAPC.Client.Essentials.Models
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;

    using ZAPC.Documents.Interfaces;
    using ZAPC.Documents.Statuses;

    public class PacketEpd : IFileNameContainer, ILocked
    {
        public static Status Status { get; } = Statuses.PacketEpdStatus;

        public string FileName { get; set; }

        public DateTime DateTime { get; set; }

        public int Amount { get; set; }

        public int DocInPackageCount { get; set; }

        public bool IsLocked { get; set; }

        public override bool Equals(object obj)
        {
            if (obj is PacketEpd packet)
                return FileName == packet.FileName;

            return false;
        }

        [SuppressMessage("ReSharper", "StyleCop.SA1407", Justification = "Autogenerated by Resharper")]
        public override int GetHashCode()
        {
            var hashCode = -169514602;
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(FileName);
            hashCode = hashCode * -1521134295 + DateTime.GetHashCode();
            hashCode = hashCode * -1521134295 + Amount.GetHashCode();
            hashCode = hashCode * -1521134295 + DocInPackageCount.GetHashCode();
            return hashCode;
        }
    }
}
